version: "2"
services:
    deployfish:
        image: "deployfish:latest"
        container_name: "deployfish"
        hostname: "deployfish"
        command: /deployfish/bin/dbdump2bucket.py
        env_file:
            - "/etc/context.d/deployfish.env"

