# asg.yml
#
# This defines a service with a load balancer that has a dedicated autoscaling
# group.
# 

services:
  - name: my-service
    cluster: my-cluster
    count: 2
    autoscalinggroup_name: my-asg
    load_balancer:
      service_role_arn: arn:aws:iam::123445564666:role/ecsServiceRole
      load_balancer_name: my-elb
      container_name: my-service
      container_port: 80
    family: my-service
    network_mode: bridge
    task_role_arn: arn:aws:iam::123445564666:role/ecsTaskRole
    containers:
      - name: my-service
        image: 123445564666.dkr.ecr.us-west-2.amazonaws.com/my-service:0.1.0
        cpu: 128
        memory: 256
        ports:
          - "80"
        environment:
          - S3_BUCKET=my-bucket
